### ISSUE TITLE
I tried to add my Project

### ISSUE THREAD

**Issue by bhbmaster** [pomber/covid19#113]
I tried to add my project to "Projects using this dataset" however its not showing up in 
https://github.com/pomber/covid19

I am not a collaboration expert. So I think I was missing a step. 

Here is what I did:

I clicked on "+Add yours" then appended my item at the bottom of the appropriate list then hit "Propose Change":

My edit was something like this:

- [covid19.py](http://www.infotinks.com/coronavirus-dashboard-covid19-py/)([repo](https://github.com/bhbmaster/covid19)): Charts in [normal](http://www.infotinks.com/covid19/covid19-normal.html) and [log](http://www.infotinks.com/covid19/covid19-log.html) axes, shows ratio of changes per day as well.

**Comment by pomber** [comment]
Hi, post a screenshot where you are having trouble. Also, you can google how to make a pull request on GitHub.
