### ISSUE TITLE
enable CORS server-side.

### ISSUE THREAD

**Issue by raedinkhaled** [pomber/covid19#119]
Please could you enable CORS server-side?

**Comment by pomber** [comment]
As far as I know, this doesn't need CORS enabled, it's a GET without extra headers. Anyway, it's hosted using GitHub Pages, I can't change the response.

**Comment by emilenriquez** [comment]
@raedinkhaled  were you able to solve your problem?

**Comment by raedinkhaled** [comment]
> @raedinkhaled were you able to solve your problem?

yes, I was using Nuxt Js and my solution was to use Fetch instead of Axios Get
