### ISSUE TITLE
Data not actual

### ISSUE THREAD

**Issue by SuchByte** [pomber/covid19#12]
The description says "Updated three times a day using GitHub Actions." but the last data (Germany) is from 2020-03-17 and today is 2020-03-18. In your json there are 9257 currently infected and the data of CSSEGISandData/COVID-19 says there are already 11.973.

I hope you can fix this.

**Comment by pomber** [comment]
Hey, I get the confirmed cases data from https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv. It doesn't have the data from 2020-03-18 yet.

**Comment by thomas-alrek** [comment]
Seems like it was just recently updated. Would it be a problem to run the action more often than 3 times a day?

**Comment by pomber** [comment]
> but the data seems to be one day behind.

which data? and compared to what?
