### ISSUE TITLE
Testing counts

### ISSUE THREAD

**Issue by andher1802** [pomber/covid19#123]
If it's a data issue please **check the source repo first**. We use the data from these files:

- [Confirmed csv](https://git.io/JvyQR)
- [Deaths csv](https://git.io/JvyQ8)
- [Recovered csv](https://git.io/JvHaX)

If the error is there too, open an issue in that repo.

Is there any option to add testing numbers, to calculate the rate of postive tests daily.

**Comment by pomber** [comment]
Nope, the data source repo isn't publishing testing numbers
