### ISSUE TITLE
How to fetch multiple country data in android?

### ISSUE THREAD

**Issue by gdkali** [pomber/covid19#155]
![photo_2020-04-15_15-20-30](https://user-images.githubusercontent.com/28677797/79324105-b595bf80-7f2c-11ea-8385-c7a8979ceba0.jpg)

I don't know how to fetch multiple country data in android. I can fetch a single country data I cannot iterate for all.please help me to find a way

**Comment by pomber** [comment]
Hi, since the question isn't really related to the dataset try asking on https://stackoverflow.com/
