### ISSUE TITLE
cannot see the en.wiktionary.org/wiki/R₀

### ISSUE THREAD

**Issue by czyborra** [pomber/covid19#161]
of all the analyses derived from and listed on https://github.com/pomber/covid19/ of which i like https://paroj.github.io/arewedeadyet/ the most i couldnot yet find any single one charting the spacetime evolution of the epidemiological https://en.wikipedia.org/wiki/basic_reproduction_number  https://en.wiktionary.org/wiki/R₀ supposed to have fallen from >1.0 via 0.9 to now 0.7 in Germany this week, so can somebody quicker than me in the necessary calculations add that somewhere?

**Comment by pomber** [comment]
Hi, maybe you can try to ask that in one of the projects showing similar info, almost all the projects in the list have links to their repos.

**Comment by czyborra** [comment]
so i did, thank you!
