### ISSUE TITLE
data are taking too long to update

### ISSUE THREAD

**Issue by yungfarz** [pomber/covid19#163]
pls why is the cases taking too long to update, how can that be improved

**Comment by pomber** [comment]
what do you mean? data is updated as usual as far as I know

**Comment by yungfarz** [comment]
> what do you mean? data is updated as usual as far as I know

dont worry about that agian, but can US in countries be changed to USA or United State Of America does not really sound well using US to represent it.

**Comment by pomber** [comment]
All the country names come from the data source, I agree some names are not the best, but we won't change names in this repo. You can open an issue in the source repo if you want.
