### ISSUE TITLE
timeseries for US states?

### ISSUE THREAD

**Issue by vangalder** [pomber/covid19#164]
What would the level of effort be for you to provide a historical analysis identical to timeseries.json but for US states?

In order to compile that data from JHU, I would currently have to make an API call for every single date since 2020-01-22.  (i.e. https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-16-2020.csv)

Make sense?

**Comment by pomber** [comment]
Hi, I prefer not to add more stuff to this repo. But forking this repo and modifying it to your needs shouldn't be a lot of work.
