### ISSUE TITLE
Tunisia's Data for today is the same as yestrday and missing 2 new confirmed cases.

### ISSUE THREAD

**Issue by nkmRex** [pomber/covid19#169]
If it's a data issue please **check the source repo first**. We use the data from these files:

- [Confirmed csv](https://git.io/JvyQR)
- [Deaths csv](https://git.io/JvyQ8)
- [Recovered csv](https://git.io/JvHaX)

If the error is there too, open an issue in that repo.

**Comment by pomber** [comment]
Have you checked if the error is present in the source data?

**Comment by nkmRex** [comment]
Hi,

I’ve checked and the source has the correct data.

R,
N

**Comment by pomber** [comment]
where have you checked? could you be more specific on what days and what are the wrong and correct numbers?

**Comment by nkmRex** [comment]
The mistake is in the total confirmed cases for Tunisia for the 18th of March 2020.
On the 17th they had a total of 864 Confirmed cases, and on the 18th 866 confirmed cases, so +2 new cases.
I found out about the mistake because I always double check with the Tunisian ministry of health.
After that, I went to WHO’s website and then Jhons Hopkins and they both have the correct number of confirmed cases for the 18th of march which is 866.

R,
N
On 19 Apr 2020, 21:48 +0700, Rodrigo Pombo <notifications@github.com>, wrote:

where have you checked? could you be more specific on what days and what are the wrong and correct numbers?

**Comment by pomber** [comment]
The links for the source data are here:

> If it's a data issue please **check the source repo first**. We use the data from these files:
> 
> * [Confirmed csv](https://git.io/JvyQR)
> * [Deaths csv](https://git.io/JvyQ8)
> * [Recovered csv](https://git.io/JvHaX)
> 
> If the error is there too, open an issue in that repo.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv is showing 864 for the 18th.

**Comment by nkmRex** [comment]
Sure, they do have the error there. Thanks pomber.
On 19 Apr 2020, 22:30 +0700, Rodrigo Pombo <notifications@github.com>, wrote:

The links for the source data are here:

If it's a data issue please check the source repo first. We use the data from these files:

  *   Confirmed csv<https://git.io/JvyQR>
  *   Deaths csv<https://git.io/JvyQ8>
  *   Recovered csv<https://git.io/JvHaX>

If the error is there too, open an issue in that repo.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv is showing 864 for the 18th.
