### ISSUE TITLE
Data not available for April 23rd, 2020 

### ISSUE THREAD

**Issue by headrohit96** [pomber/covid19#178]
Data unavailable for April 23rd, 2020.
Data present here https://github.com/CSSEGISandData/COVID-19.
Please check!

**Comment by raph-dav** [comment]
+1 :)

**Comment by akshayajeevan** [comment]
This is because delay of data update by CSSE. 

@pomber need to add a morning time (6:15) for the github action cron?

**Comment by backtrackbaba** [comment]
Would it be possible to trigger an update manually ?

**Comment by yungfarz** [comment]
data is just too slow it has updated on CSSE website, maybe this repo is slow

**Comment by jsanjay63** [comment]
The scheduler needs to be changed to execute every hour/once in 2 hrs at least. It won't do any harm even in case if we don't have any new updates to be fetched.

**Comment by pomber** [comment]
Sorry, it's updated now.
 
CSSE updated the data 3.55am UTC (unusually late). This repo checks at 0.15am, 2.15am and 12.15pm, so it took more than 8hs to get the new data.

I'll schedule more runs during those hours.

**Comment by backtrackbaba** [comment]
Thank you @pomber for the quick response!

**Comment by headrohit96** [comment]
Thanks, @pomber!

**Comment by yungfarz** [comment]
> 
> 
> Sorry, it's updated now.
> 
> CSSE updated the data 3.55am UTC (unusually late). This repo checks at 0.15am, 2.15am and 12.15pm, so it took more than 8hs to get the new data.
> 
> I'll schedule more runs during those hours.

hmm pomber if  possible please allow the repo check  0.15am, 2.15am and 12.15pm, 3.15pm ,

**Comment by pomber** [comment]
> hmm pomber if possible please allow the repo check 0.15am, 2.15am and 12.15pm, 3.15pm ,

Added more runs here: https://github.com/pomber/covid19/commit/d3fb9aaaf4b029990f9dd894fb826463f4513a33

**Comment by yungfarz** [comment]
> 
> 
> Sorry, it's updated now.
> 
> CSSE updated the data 3.55am UTC (unusually late). This repo checks at 0.15am, 2.15am and 12.15pm, so it took more than 8hs to get the new data.
> 
> I'll schedule more runs during those hours.

please schedule many more run if possible every 1 hour

imformation need to fast and accurate 

thank you
