### ISSUE TITLE
Problems with Brazil data

### ISSUE THREAD

**Issue by yudivian** [pomber/covid19#218]
Today (2020-6-5), Brazil is reported with 0 recovered and yesterday was with 254963.

**Comment by dionatamsouza** [comment]
Here President Bolsonaro is intentionally underreporting the data. Tragic. World shame. Consider using data from volunteer researchers in the datasets on the Brasil.IO website, they are kept in the project https://github.com/turicas/covid19-br.
Sorry about our nation, we elected an idiotic president.
