### ISSUE TITLE
Issue with data for Poland

### ISSUE THREAD

**Issue by AdiMustBeFunny** [pomber/covid19#23]
I have an issue with the data for Poland. It shows 13 people who have recovered on 18th but only 1 person on 19th. Shouldn't it remain the same or increase?

**Comment by pomber** [comment]
That's what's reported on the source: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv

Check if there's an issue in their repo.

**Comment by AdiMustBeFunny** [comment]
Data seems wrong maybe they made a mistake. Thanks for fast reply. I will close the issue here and post it on their repo
