### ISSUE TITLE
Hi!  Congrats about the code, nice job!...    On December 15 and 16, the Recoveries # for the US is missing (it is returning 0). It may be that Johns Hopkins may not have reported it either. However, there is a way to obtain by adding up by state.  If I recall correctly,  I was able to look at the US by state in your earlier versions?... is that info still accessible?  is the entry for US recoveries an issue from the code?...  Thank you!

### ISSUE THREAD

**Issue by RafaelMendozaArriaga** [pomber/covid19#232]
If it's a data issue please **check the source repo first**. We use the data from these files:

- [Confirmed csv](https://git.io/JvyQR)
- [Deaths csv](https://git.io/JvyQ8)
- [Recovered csv](https://git.io/JvHaX)

If the error is there too, open an issue in that repo.

**Comment by RiccardoBorchi** [comment]
This issue has not been resolved yet. Recovered data for USA is still 0.

**Comment by pomber** [comment]
Hi, have you verified if the error is present on the source dataset?

**Comment by jaszium** [comment]
> Hi, have you verified if the error is present on the source dataset?

Based on the link given above: [Recovered.csv](https://git.io/JvHaX),
I can confirm / verify that US Recoveries become 0 on 2020 Dec 14, as shown in the image below:
![image](https://user-images.githubusercontent.com/58339115/103850803-34e2a900-50e3-11eb-929a-4f94995e8b89.png)
It stays at 0 up to today, and the last non-zero date was 2020 Dec 13, which stated US Recoveries was 6298082 patients.
Therefore @pomber, your code is working correctly, but the data from [CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19) has this issue.
Also, I have gone and found this same [issue](https://github.com/CSSEGISandData/COVID-19/issues/3464) present on their Repo as well.
Sincerely, an avid user of your code making a Python GUI app with it in Windows 10.

**Comment by pomber** [comment]
thanks for looking it up @jaszium
