### ISSUE TITLE
Bad year for data for 2021

### ISSUE THREAD

**Issue by entorb** [pomber/covid19#233]
Hi, I just discovered that in https://pomber.github.io/covid19/timeseries.json the latest data points are wrongly set to year 2020 instead of 2021:

`    {
      "date": "2020-12-30",
      "confirmed": 51405,
      "deaths": 2181,
      "recovered": 41612
    },
    {
      "date": "2020-12-31",
      "confirmed": 51526,
      "deaths": 2191,
      "recovered": 41727
    },
    {
      "date": "2020-1-1",
      "confirmed": 51526,
      "deaths": 2191,
      "recovered": 41727
    }
  ],`

**Comment by cthiebaud** [comment]
https://github.com/pomber/covid19/issues/234#issue-777589090

**Comment by pomber** [comment]
Thanks, I don't have access to a computer right now. If anyone can submit a PR I'll try to merge it.

**Comment by pomber** [comment]
Should be fixed now, let me know otherwise.

**Comment by entorb** [comment]
Thanks for the fast fix!
