### ISSUE TITLE
hard-coded 2020 year in update.js

### ISSUE THREAD

**Issue by cthiebaud** [pomber/covid19#234]
Below the comment "// HACK: CSVs have different date formats" in update.js, the year "2020" is hard-coded.

This has a negative effect on the data for year 2021 ;)

I checked the source repo for this file:

- [Confirmed csv](https://git.io/JvyQR)

and the the error is **not** there.

**Comment by cthiebaud** [comment]
This has negative effect on the display on [covid.aequologica.net](https://covid.aequologica.net/?2020-01-01,7,BE,DE,FR,IT,day,deaths,lin,per,_) as well:

<img width="381" alt="Screenshot 2021-01-03 at 08 27 03" src="https://user-images.githubusercontent.com/773520/103473905-d98c8000-4d9d-11eb-9d23-cb48c0343c76.png">

**Comment by cthiebaud** [comment]
FYI, I coded a counter-hack in may code : https://github.com/cthiebaud/cthiebaud.github.io/commit/c0067bd59cd3b081e2b0e1c4d3dd5b0296cdb030
;)

**Comment by pomber** [comment]
Thanks, it should be fixed now.
