### ISSUE TITLE
Lasted Updated Timestamp

### ISSUE THREAD

**Issue by parrfolio** [pomber/covid19#27]
Thank you for providing this data. Can you provide the last updated timestamp in the object? That would be helpful to understand the last time the numbers where run.

**Comment by Maanuj-Vora** [comment]
As per my understanding, JSON objects come with a Last-Modified attribute in it, so what I would do to get the last updated timestamp would be the following,
```javascript
var data = $.ajax({
                url: "https://pomber.github.io/covid19/timeseries.json",
                success: function(response) {
                    console.log("Data was last modified: " + data.getResponseHeader("Last-Modified"));
                }
            });
```

That will output the last modification of the JSON object to console.

**Comment by pomber** [comment]
I think GitHub Pages doesn't let you change the headers.  
But it is safe to assume that the last update was at midnight (UTC) from the last date in the time-series.
