### ISSUE TITLE
Ruby Adapter

### ISSUE THREAD

**Issue by shaunlawrencecarland** [pomber/covid19#30]
Hi!  I created a Ruby gem that can send GET requests to this URL with the region that they're looking for.  You can access it here:

https://github.com/everythings-cancelled/pomber_covid19

I was thinking about adding in the README a list of adapters/wrappers for this data that are available.  Would people have objections to that?

**Comment by pomber** [comment]
No objections! If you want, you can group the different projects in the readme by category (something like: visualizations, adapters/APIs, analysis)

**Comment by pomber** [comment]
I added this to the readme
