### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [pomber/covid19#42]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

http://open-source-covid-19.weileizeng.com/

Cheers!

**Comment by WeileiZeng** [comment]
Meanwhile, I am curious that does this static json API encounter any "github page usage limit" issue? How much visit can it handle?

**Comment by pomber** [comment]
Hey, thanks.

> Meanwhile, I am curious that does this static json API encounter any "github page usage limit" issue? How much visit can it handle?

Not yet, apparently there's ["a soft bandwidth limit of 100GB per month"](https://help.github.com/en/github/working-with-github-pages/about-github-pages#guidelines-for-using-github-pages) but no idea how much I have used.

**Comment by WeileiZeng** [comment]
the Insight-Traffic section may give you an idea on the current usage.
