### ISSUE TITLE
US deaths have dropped to zero

### ISSUE THREAD

**Issue by nicholasmccullum** [pomber/covid19#50]
Hey @pomber - awesome data source you've built here! I thought you'd want to know that US deaths have dropped to 0 over the last few dates.

**Comment by pomber** [comment]
You mean deaths or recovered?

Just checked, the last item for the US is
```json
    {
      "date": "2020-3-22",
      "confirmed": 33272,
      "deaths": 417,
      "recovered": 0
    }
```

**Comment by DasHammett** [comment]
I think the issue has to do with the source files not being updated anymore. See
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by nicholasmccullum** [comment]
Does this mean this data source is no longer functional? Trying to understand the implications of this.

**Comment by pomber** [comment]
Could you be more specific on what data are you talking about? Is it deaths? recovered? US? global?

**Comment by energee** [comment]
From CSSEGISandData repo:

---DEPRICATED WARNING---
The files below will no longer be updated. With the release of the new data structure, we are updating our time series tables to reflect these changes. Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data.

time_series_19-covid-Confirmed.csv
time_series_19-covid-Deaths.csv
time_series_19-covid-Recovered.csv

**Comment by energee** [comment]
Recovered os no longer being tracked by JHU. Issue can be closed.
