### ISSUE TITLE
Todays values are the same as yesterday

### ISSUE THREAD

**Issue by bauefi** [pomber/covid19#53]
Today the values stopped updating. I think the values today and yesterday are the same for all countries

**Comment by bauefi** [comment]
> 
> 
> Today the values stopped updating. I think the values today and yesterday are the same for all countries

**Comment by bauefi** [comment]
John Hopkins depreceated the following files in their repository: 

time_series_19-covid-Confirmed.csv
time_series_19-covid-Deaths.csv
time_series_19-covid-Recovered.csv

They are asking developers to use the following files instead:

time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_global.csv

Does this cause the issue?

**Comment by pepi99** [comment]
The values are indeed the same as yesterday!

**Comment by pomber** [comment]
Should be fixed now
