### ISSUE TITLE
CSSEGISandData / COVID-19 breaking changes

### ISSUE THREAD

**Issue by mylo7s** [pomber/covid19#54]
Please reference the new files **time_series_covid19_confirmed_global.csv** and **time_series_covid19_deaths_global.csv**

-------------------------------------------------------------------------------------------------------------
**News from CSSEGISandData / COVID-19 repository**
---DEPRECATED WARNING---
The files below will no longer be updated. With the release of the new data structure, we are updating our time series tables to reflect these changes. Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data.

time_series_19-covid-Confirmed.csv
time_series_19-covid-Deaths.csv
time_series_19-covid-Recovered.csv

**Comment by nicolaschenet** [comment]
https://github.com/pomber/covid19/pull/57

**Comment by pomber** [comment]
Dup #37
