### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by deme87** [pomber/covid19#55]
Hi and thanks for the great work.
It seems that the data for the 23/03 and 24/04 seem to be exactly the same.
Thanks

**Comment by entorb** [comment]
Reason is that the JHU Source changed, see their Warning in the [readme](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/README.md):



---DEPRICATED WARNING---
The files below will no longer be updated. With the release of the new data structure, we are updating our time series tables to reflect these changes. Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data.

time_series_19-covid-Confirmed.csv
time_series_19-covid-Deaths.csv
time_series_19-covid-Recovered.csv

**Comment by parmentelat** [comment]
this should be taken care of with pr #57

**Comment by pomber** [comment]
should be fixed now

**Comment by deme87** [comment]
Perfect thanks! Is the recovered data not valid anymore?

**Comment by pomber** [comment]
Apparently not. But I keep updating the json with the data from [the recovered csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv) just in case

**Comment by deme87** [comment]
Perfect thanks.
