### ISSUE TITLE
All recovered values are null

### ISSUE THREAD

**Issue by rlmckenney** [pomber/covid19#74]
The current data set is now reporting all recovered values as null.

The upstream data source has changed their data structure and file naming convention. [See the README.](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/README.md)

`time_series_19-covid-Recovered.csv` is no longer available.  It has been replaced with `time_series_covid19_recovered_global.csv`.

**Comment by pomber** [comment]
Yes, I've already changed the filename, but they are using different date formats for the recovered csv. I'm working on a fix right now.

**Comment by pomber** [comment]
Ok, should be fixed now.

**Comment by RemiTheWarrior** [comment]
@pomber it seems there still are null values for 25th of March

**Comment by pomber** [comment]
> @pomber it seems there still are null values for 25th of March

Yep, that's because there isn't data reported for that day in [the source csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv).

**Comment by RemiTheWarrior** [comment]
Ah ok so is it likely to change in the following days then ?

**Comment by pomber** [comment]
> Ah ok so is it likely to change in the following days then ?

I don't know.

**Comment by RemiTheWarrior** [comment]
Thanks for the hard work !
