### ISSUE TITLE
China numbers are incorrect.

### ISSUE THREAD

**Issue by tribbin** [pomber/covid19#81]
As of march 27th:

In JSON: 3291
Real: 26853

**Comment by pomber** [comment]
From the issue template:

---

If it's a data issue please **check the source repo first**. We use the data from these files:

- [Confirmed csv](https://git.io/JvyQR)
- [Deaths csv](https://git.io/JvyQ8)
- [Recovered csv](https://git.io/JvHaX)

If the error is there too, open an issue in that repo.

---

**Comment by pomber** [comment]
Closing this. Please reopen if the numbers are wrong compared to the source csv.

**Comment by tribbin** [comment]
Thank you for your response. My issue has already been submitted multiple times.

Candidate for your list: https://github.com/tribbin/covid19nl

Time-shifted logarithmic data representation for The Netherlands, that illustrates how Italy serves as a 12-days prognose for our country, with other countries as context.
